general:
  instance_name: Custom SearXNG
  enable_metrics: true

search:
  safe_search: 0
  language: "en"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
